/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  ApiNewAccount: () => import('#controllers/api_new_account_controller'),
  Jobs: () => import('#controllers/jobs_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Projects: () => import('#controllers/projects_controller'),
  Session: () => import('#controllers/session_controller'),
}
