/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AssetSchema extends BaseModel {
  static $columns = ['byteSize', 'checksumSha256', 'createdAt', 'height', 'id', 'kind', 'metadata', 'mimeType', 'providerAssetId', 'providerId', 'source', 'status', 'storageKey', 'updatedAt', 'width'] as const
  $columns = AssetSchema.$columns
  @column()
  declare byteSize: bigint | number
  @column()
  declare checksumSha256: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare metadata: any | null
  @column()
  declare mimeType: string
  @column()
  declare providerAssetId: string | null
  @column()
  declare providerId: string | null
  @column()
  declare source: string
  @column()
  declare status: string
  @column()
  declare storageKey: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare width: number | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GenerationJobSchema extends BaseModel {
  static $columns = ['attemptCount', 'completedAt', 'costMinor', 'createdAt', 'errorCode', 'errorMessage', 'id', 'idempotencyKey', 'jobType', 'providerConfigSnapshot', 'startedAt', 'status', 'updatedAt', 'videoId'] as const
  $columns = GenerationJobSchema.$columns
  @column()
  declare attemptCount: number
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare costMinor: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errorCode: string | null
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idempotencyKey: string
  @column()
  declare jobType: string
  @column()
  declare providerConfigSnapshot: any | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare videoId: number
}

export class ProjectSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'ownerId', 'sourcePrompt', 'status', 'title', 'updatedAt'] as const
  $columns = ProjectSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ownerId: number
  @column()
  declare sourcePrompt: string
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProviderConfigSchema extends BaseModel {
  static $columns = ['capability', 'config', 'costMinorPerUnit', 'createdAt', 'enabled', 'id', 'model', 'promptVersion', 'providerId', 'updatedAt'] as const
  $columns = ProviderConfigSchema.$columns
  @column()
  declare capability: string
  @column()
  declare config: any
  @column()
  declare costMinorPerUnit: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare model: string
  @column()
  declare promptVersion: string | null
  @column()
  declare providerId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProviderRouteSchema extends BaseModel {
  static $columns = ['capability', 'createdAt', 'fallbackConfigId', 'id', 'primaryConfigId', 'updatedAt'] as const
  $columns = ProviderRouteSchema.$columns
  @column()
  declare capability: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fallbackConfigId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare primaryConfigId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RenderJobSchema extends BaseModel {
  static $columns = ['attemptCount', 'completedAt', 'createdAt', 'errorCode', 'errorMessage', 'id', 'idempotencyKey', 'quality', 'renderSpecSnapshot', 'resultAssetId', 'startedAt', 'status', 'updatedAt', 'videoId'] as const
  $columns = RenderJobSchema.$columns
  @column()
  declare attemptCount: number
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errorCode: string | null
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idempotencyKey: string
  @column()
  declare quality: string
  @column()
  declare renderSpecSnapshot: any
  @column()
  declare resultAssetId: number | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare videoId: number
}

export class SceneAssetSchema extends BaseModel {
  static $columns = ['assetId', 'createdAt', 'role', 'sceneId', 'sequenceNo'] as const
  $columns = SceneAssetSchema.$columns
  @column()
  declare assetId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare role: string
  @column({ isPrimary: true })
  declare sceneId: number
  @column()
  declare sequenceNo: number
}

export class SceneSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'sceneSpec', 'sequenceNo', 'specVersion', 'state', 'updatedAt', 'videoId'] as const
  $columns = SceneSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sceneSpec: any
  @column()
  declare sequenceNo: number
  @column()
  declare specVersion: number
  @column()
  declare state: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare videoId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VideoSchema extends BaseModel {
  static $columns = ['createdAt', 'durationMs', 'fps', 'height', 'id', 'projectId', 'status', 'updatedAt', 'width'] as const
  $columns = VideoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMs: number | null
  @column()
  declare fps: number
  @column()
  declare height: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare projectId: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare width: number
}
